// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACC1ljCQFcyeZxH_FRbpeFiuvzkLIOyU8',
    appId: '1:172250705816:web:2bab3ddddfb003523f85ed',
    messagingSenderId: '172250705816',
    projectId: 'block-management-a8ba0',
    authDomain: 'block-management-a8ba0.firebaseapp.com',
    storageBucket: 'block-management-a8ba0.appspot.com',
    measurementId: 'G-DLWRTSVGXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtoiKGnbX3j0CWTx1CEId_k5pIjJ2SDU',
    appId: '1:172250705816:android:fa727459bba7b9af3f85ed',
    messagingSenderId: '172250705816',
    projectId: 'block-management-a8ba0',
    storageBucket: 'block-management-a8ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK5f8kazwcCTzPHzqqkjwKtcAodB00M-A',
    appId: '1:172250705816:ios:91e13f4d4aed6bae3f85ed',
    messagingSenderId: '172250705816',
    projectId: 'block-management-a8ba0',
    storageBucket: 'block-management-a8ba0.appspot.com',
    iosBundleId: 'com.example.examBlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK5f8kazwcCTzPHzqqkjwKtcAodB00M-A',
    appId: '1:172250705816:ios:91e13f4d4aed6bae3f85ed',
    messagingSenderId: '172250705816',
    projectId: 'block-management-a8ba0',
    storageBucket: 'block-management-a8ba0.appspot.com',
    iosBundleId: 'com.example.examBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACC1ljCQFcyeZxH_FRbpeFiuvzkLIOyU8',
    appId: '1:172250705816:web:af33624cb805f3533f85ed',
    messagingSenderId: '172250705816',
    projectId: 'block-management-a8ba0',
    authDomain: 'block-management-a8ba0.firebaseapp.com',
    storageBucket: 'block-management-a8ba0.appspot.com',
    measurementId: 'G-Y6CM5V6333',
  );
}
